services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: messenger-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules