INSERT INTO chats DEFAULT VALUES;

INSERT INTO chats DEFAULT VALUES;

INSERT INTO chats DEFAULT VALUES;

INSERT INTO chats DEFAULT VALUES;

INSERT INTO chats DEFAULT VALUES;

INSERT INTO chats DEFAULT VALUES;

SELECT * FROM chats