spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/messenger
    username: ${DB_USER:messenger}
    password: ${DB_PASSWORD:messenger}

jwt:
  secret: ${JWT_SECRET}